//
//  ViewController.swift
//  MarketMakerPro
//
//  Created by Andy Alleyne on 12/15/18.
//  Copyright © 2018 AlleyneVentures. All rights reserved.
//

import UIKit
import GoogleMobileAds

class ViewController: UIViewController, GADBannerViewDelegate {

    //creating Banner ads - move one to each new controller view i create
    
    @IBOutlet weak var bannerMarketView: GADBannerView!
    @IBOutlet weak var bannerWatchlistView: GADBannerView!
    @IBOutlet weak var bannerDetailView: GADBannerView!
    @IBOutlet weak var bannerOptionsView: GADBannerView!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        //declared the banners
    
        bannerMarketView.adUnitID = "ca-app-pub-7563192023707820/6176021227"
        bannerWatchlistView.adUnitID = "ca-app-pub-7563192023707820/6433496934"
        bannerDetailView.adUnitID = "ca-app-pub-7563192023707820/2466331764"
        bannerOptionsView.adUnitID = "ca-app-pub-7563192023707820/6377656611"
        
        bannerMarketView.rootViewController = self
        bannerWatchlistView.rootViewController = self
        bannerDetailView.rootViewController = self
        bannerOptionsView.rootViewController = self
        
        
        //created a targeted request for ADs for bannerMarketView
        let requestMarket = GADRequest()
        let requestCompany = GADRequest()
        let requestKeywords = GADRequest()
        requestMarket.contentURL = "https://www.nasdaq.com"
        requestCompany.contentURL = "https://www.schwab.com"
        requestKeywords.keywords = ["trading", "stocks", "options", "ETF", "hedgefund","buy", "sell", "margin"]
        
        //loads provide targeting information i need to investigate
        bannerMarketView.load(requestMarket)
        bannerOptionsView.load(GADRequest())
        bannerDetailView.load(requestKeywords)
        
        //auto is just blind ads
        bannerWatchlistView.isAutoloadEnabled = true
    }

    //MARK: event generated by ads
    
    /// Tells the delegate an ad request loaded an ad.
    func adViewDidReceiveAd(_ bannerView: GADBannerView) {
        
        //animate the AD into view, could all animation at this point for ADs
        
        print("adViewDidReceiveAd")
    }
    
    /// Tells the delegate an ad request failed.
    func adView(_ bannerView: GADBannerView,
                didFailToReceiveAdWithError error: GADRequestError) {
        print("adView:didFailToReceiveAdWithError: \(error.localizedDescription)")
    }
    
    /// Tells the delegate that a full-screen view will be presented in response
    /// to the user clicking on an ad.
    func adViewWillPresentScreen(_ bannerView: GADBannerView) {
        print("adViewWillPresentScreen")
    }
    
    /// Tells the delegate that the full-screen view will be dismissed.
    func adViewWillDismissScreen(_ bannerView: GADBannerView) {
        print("adViewWillDismissScreen")
    }
    
    /// Tells the delegate that the full-screen view has been dismissed.
    func adViewDidDismissScreen(_ bannerView: GADBannerView) {
        print("adViewDidDismissScreen")
    }
    
    /// Tells the delegate that a user click will open another app (such as
    /// the App Store), backgrounding the current app.
    func adViewWillLeaveApplication(_ bannerView: GADBannerView) {
        print("adViewWillLeaveApplication")
    }
    
    

}

